# Generated by Django 4.2.7 on 2026-01-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField(verbose_name='旅行ID')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('duration', models.FloatField(verbose_name='旅行周期（天）')),
                ('traveler_name', models.CharField(max_length=50, verbose_name='旅行者姓名')),
                ('traveler_age', models.FloatField(verbose_name='旅行者年龄')),
                ('traveler_gender', models.CharField(max_length=10, verbose_name='旅行者性别')),
                ('traveler_nationality', models.CharField(max_length=30, verbose_name='旅行者国籍')),
                ('accommodation_type', models.CharField(max_length=30, verbose_name='住宿类型')),
                ('accommodation_cost', models.FloatField(verbose_name='住宿费用')),
                ('transportation_type', models.CharField(max_length=30, verbose_name='交通类型')),
                ('transportation_cost', models.FloatField(verbose_name='交通费用')),
                ('month', models.IntegerField(verbose_name='出行月份')),
                ('season', models.CharField(max_length=10, verbose_name='出行季节')),
                ('age_segment', models.CharField(max_length=10, verbose_name='年龄分段')),
                ('total_cost', models.FloatField(verbose_name='总费用')),
                ('cost_range', models.CharField(max_length=10, verbose_name='费用区间')),
                ('region', models.CharField(max_length=20, verbose_name='地域')),
            ],
            options={
                'verbose_name': '旅行记录',
                'verbose_name_plural': '旅行记录',
            },
        ),
    ]
